[package]
name = "intcode_computer"
version = "0.1.0"
authors = ["Pierre Chevalier <pierrechevalier83@gmail.com>"]
edition = "2018"

[lib]
name = "intcode_computer"
path = "src/lib.rs"

[dependencies]
mockstream = "0.0.3"
